// Generated by CoffeeScript 1.3.3
(function() {
  var App;

  App = {
    currentImage: 0,
    init: function() {
      _.bindAll(this);
      _.each($('.image'), this.loadImage);
      _.each($('.full-image'), this.loadImage);
      $(window).bind('scroll', this.position);
      Mousetrap.bind('left', this.previousImage);
      Mousetrap.bind('right', this.nextImage);
      Mousetrap.bind('up', this.previousImage);
      Mousetrap.bind('down', this.nextImage);
      $('a.to-credits').bind('click', this.toCredits);
      this.initVideo();
      SC.whenStreamingReady(this.initAudio);
    },
    loadImage: function(el) {
      var $el, $i, i, src;
      $el = $(el);
      src = $el.data('src');
      i = new Image();
      i.src = src;
      $i = $(i);
      $el.append(i);
    },
    position: function(e) {
      var h, scrollTop, y;
      scrollTop = $('body').scrollTop();
      h = $('#left').height();
      y = scrollTop;
      if (scrollTop >= h) {
        $('body').scrollTop(0);
      }
      $('#right').css({
        top: "" + y + "px"
      });
    },
    nextImage: function() {
      this.showImage(this.currentImage + 1);
      return false;
    },
    previousImage: function() {
      this.showImage(this.currentImage - 1);
      return false;
    },
    showImage: function(n) {
      console.log('showImage', n);
      if (n < 0) {
        return;
      }
      if (n > 12) {
        return;
      }
      $('body').animate({
        scrollTop: n * 1000
      }, 420);
      this.currentImage = n;
    },
    toCredits: function(e) {
      e.preventDefault();
      this.showImage(12);
    },
    initVideo: function() {
      var iframe, player,
        _this = this;
      iframe = $('#vimeo')[0];
      player = $f(iframe);
      player.addEvent('ready', function() {
        console.log('player ready');
      });
      player.addEvent('play', function() {
        console.log('play?');
      });
    },
    initAudio: function() {
      var _this = this;
      console.log('initAudio');
      SC.stream("/tracks/5465310", function(sound) {
        _this.audio = sound;
        return _this.audio.play();
      });
    }
  };

  App.init();

}).call(this);
